language: ruby
sudo: false
env:
  matrix:
  - BROWSER=chromium EXT=crx
  - BROWSER=firefox EXT=xpi
  - BROWSER=webext EXT=xpi
before_script:
- git clone https://github.com/uBlockOrigin/uAssets.git ../uAssets
- openssl genrsa -out ./platform/chromium/adnauseam-first.pem 768
- openssl pkcs8 -topk8 -nocrypt -in ./platform/chromium/adnauseam-first.pem -out ./platform/chromium/adnauseam.pem
script: ./tools/make-${BROWSER}.sh all
deploy:
  provider: releases
  prerelease: true
  # https://github.com/travis-ci/travis-ci/issues/6772
  api_key:
    secure: EnAMNsPbnS2I0JDkCWiY/6WLERsUbE2Ni5j9ap8YbZt4+sJv7aSoufWZ+0TZvSwr/w5MKCCDKhwXaPfbUwvqrI+eZv6LBXhwajK9Zla25FVjtdGCwKXQ3ZU85PHgL+5FYtuSGACmQj/ruAdSgrI7PgS08e5lqSgEk6lY4y3/6fE=
  file: dist/build/adnauseam.${BROWSER}.${EXT}
  skip_cleanup: true
  on:
    repo: EntranceJew/AdNauseam
    all_branches: true
